NONPACK_CARTONTYPES = (
    'NONPACK',
    'STRETCH',
)
NONPACK_CARGOTYPES = (
    '340',
    '360'
)
NONPACK_TYPES = dict(zip(NONPACK_CARGOTYPES, NONPACK_CARTONTYPES))
PACKET_CARTONTYPES = (
    'MYA',
    'MYB',
    'MYC',
    'MYD',
    'MYE',
)
FRAGILITY_CARGOTYPES = (
    310,
)
ADD_ORDERS_URL = 'http://localhost:8000/api/v1/order'
