"""fix Cartontype

Revision ID: 1813e3059a41
Revises: 7536c8737d40
Create Date: 2023-06-10 20:11:19.750991

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '1813e3059a41'
down_revision = '7536c8737d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartontypes', sa.Column('length', sa.Float(), nullable=True))
    op.add_column('cartontypes', sa.Column('width', sa.Float(), nullable=True))
    op.add_column('cartontypes', sa.Column('height', sa.Float(), nullable=True))
    op.drop_constraint('cartontypes_name_key', 'cartontypes', type_='unique')
    op.drop_column('cartontypes', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartontypes', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('cartontypes_name_key', 'cartontypes', ['name'])
    op.drop_column('cartontypes', 'height')
    op.drop_column('cartontypes', 'width')
    op.drop_column('cartontypes', 'length')
    # ### end Alembic commands ###
