"""Fix typo in honest_sign models

Revision ID: 6c5543770ee6
Revises: 18a5421c6844
Create Date: 2023-06-14 22:05:36.089861

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '6c5543770ee6'
down_revision = '18a5421c6844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('honest_signs', sa.Column('honest_sign', sa.String(length=500), nullable=True))
    op.drop_constraint('honest_signs_honest_sigt_key', 'honest_signs', type_='unique')
    op.create_unique_constraint(None, 'honest_signs', ['honest_sign'])
    op.drop_column('honest_signs', 'honest_sigt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('honest_signs', sa.Column('honest_sigt', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'honest_signs', type_='unique')
    op.create_unique_constraint('honest_signs_honest_sigt_key', 'honest_signs', ['honest_sigt'])
    op.drop_column('honest_signs', 'honest_sign')
    # ### end Alembic commands ###
