"""add ProductsCargotypes

Revision ID: 43615e9edfb2
Revises: fa96458f5f63
Create Date: 2023-06-08 21:42:31.951833

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '43615e9edfb2'
down_revision = 'fa96458f5f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargotypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('products_cargotypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('cargotypes_tag', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['cargotypes_tag'], ['cargotypes.tag'], ),
    sa.ForeignKeyConstraint(['sku'], ['products.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('length', sa.Float(), nullable=True))
    op.drop_constraint('products_cargotype_key', 'products', type_='unique')
    op.drop_column('products', 'cargotype')
    op.drop_column('products', 'lenght')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('lenght', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('cargotype', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.create_unique_constraint('products_cargotype_key', 'products', ['cargotype'])
    op.drop_column('products', 'length')
    op.drop_table('products_cargotypes')
    op.drop_table('cargotypes')
    # ### end Alembic commands ###
