"""add PackingVariation, Package, Cartontype

Revision ID: b6d755242be2
Revises: 74db0d3ae7f9
Create Date: 2023-06-09 15:58:44.557900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d755242be2'
down_revision = '74db0d3ae7f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartontypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('pack_variation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderkey', sa.String(length=100), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.Column('is_recommendation', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['orderkey'], ['orders.orderkey'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cartontype_tag', sa.String(length=100), nullable=False),
    sa.Column('packing_variation_id', sa.Integer(), nullable=False),
    sa.Column('is_packaged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cartontype_tag'], ['cartontypes.tag'], ),
    sa.ForeignKeyConstraint(['packing_variation_id'], ['pack_variation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pack_variation_package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_variation_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['package_variation_id'], ['pack_variation.id'], ),
    sa.PrimaryKeyConstraint('id', 'package_variation_id', 'package_id')
    )
    op.create_table('package_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('product_sku', sa.String(length=100), nullable=True),
    sa.Column('barecode_tag', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['barecode_tag'], ['barcode_sku.barcode'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['product_sku'], ['products.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('barcode_sku', sa.Column('orderkey', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'barcode_sku', 'orders', ['orderkey'], ['orderkey'])
    op.add_column('orders', sa.Column('is_packaged', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_packaged')
    op.drop_constraint(None, 'barcode_sku', type_='foreignkey')
    op.drop_column('barcode_sku', 'orderkey')
    op.drop_table('package_products')
    op.drop_table('pack_variation_package')
    op.drop_table('packages')
    op.drop_table('pack_variation')
    op.drop_table('cartontypes')
    # ### end Alembic commands ###
