"""add status to packages, delete is_packages from orders

Revision ID: 18a5421c6844
Revises: 962e4886ac92
Create Date: 2023-06-14 10:56:11.738014

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '18a5421c6844'
down_revision = '962e4886ac92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    package_status_enum = sa.Enum('INACTIVE', 'ACTIVE', 'PACKED', name='packagestatusenum')
    package_status_enum.create(op.get_bind())
    op.drop_column('orders', 'is_packaged')
    op.add_column('packages', sa.Column('status', sa.Enum('INACTIVE', 'ACTIVE', 'PACKED', name='packagestatusenum'), nullable=False))
    op.drop_column('packages', 'is_packaged')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    package_status_enum = sa.Enum('INACTIVE', 'ACTIVE', 'PACKED', name='packagestatusenum')
    package_status_enum.drop(op.get_bind())
    op.add_column('packages', sa.Column('is_packaged', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('packages', 'status')
    op.add_column('orders', sa.Column('is_packaged', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
