"""rename ProductCargotype.cargotype_tag

Revision ID: 13fb69f466f2
Revises: 1813e3059a41
Create Date: 2023-06-11 01:10:40.412721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fb69f466f2'
down_revision = '1813e3059a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_cargotypes', sa.Column('cargotype_tag', sa.String(length=100), nullable=False))
    op.drop_constraint('products_cargotypes_cargotypes_tag_fkey', 'products_cargotypes', type_='foreignkey')
    op.create_foreign_key(None, 'products_cargotypes', 'cargotypes', ['cargotype_tag'], ['tag'])
    op.drop_column('products_cargotypes', 'cargotypes_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_cargotypes', sa.Column('cargotypes_tag', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products_cargotypes', type_='foreignkey')
    op.create_foreign_key('products_cargotypes_cargotypes_tag_fkey', 'products_cargotypes', 'cargotypes', ['cargotypes_tag'], ['tag'])
    op.drop_column('products_cargotypes', 'cargotype_tag')
    # ### end Alembic commands ###
