"""Add Imei and HosestSign models

Revision ID: 962e4886ac92
Revises: ea5db98a549f
Create Date: 2023-06-13 20:30:36.842220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962e4886ac92'
down_revision = 'ea5db98a549f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('honest_signs',
    sa.Column('honest_sigt', sa.String(length=500), nullable=True),
    sa.Column('barcode', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barcode'], ['barcode_sku.barcode'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('honest_sigt')
    )
    op.create_table('imeis',
    sa.Column('imei', sa.String(length=50), nullable=True),
    sa.Column('barcode', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barcode'], ['barcode_sku.barcode'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('imei')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imeis')
    op.drop_table('honest_signs')
    # ### end Alembic commands ###
