"""remove PackVariationPackage

Revision ID: 7536c8737d40
Revises: b6d755242be2
Create Date: 2023-06-10 17:42:09.670750

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '7536c8737d40'
down_revision = 'b6d755242be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pack_variation_package')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pack_variation_package',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('package_variation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('package_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name='pack_variation_package_package_id_fkey'),
    sa.ForeignKeyConstraint(['package_variation_id'], ['pack_variation.id'], name='pack_variation_package_package_variation_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'package_variation_id', 'package_id', name='pack_variation_package_pkey')
    )
    # ### end Alembic commands ###
