version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: legyan/packing-backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: legyan/packing-frontend:latest
    restart: always
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend


volumes:
  static_value:
  media_value:
