version: '3.3'
services:

  db-ym-pack:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  ds-ym-pack:
    image: legyan/ds-ym-pack:latest
    restart: always
    depends_on:
      - db-ym-pack
    env_file:
      - ./.env

  backend-ym-pack:
    image: legyan/backend-ym-pack:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - ds-ym-pack
    env_file:
      - ./.env

  frontend-ym-pack:
    image: legyan/frontend-ym-pack:latest
    restart: always
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend-ym-pack

    
  nginx-ym-pack:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/recipes/
    depends_on:
      - frontend-ym-pack


volumes:
  postgresql:
  static_value:
  media_value:
